Feature/java-docker-compose
diogenesviana/fiap-tech-2024 pull request #1
Opened 2024-05-02 19:47 UTC by filipexxborba

2024-05-03 00:27 UTC, rhuanpk reviewed
algumas coisas que sugeri são pura perfumaria e outras são mais técnicas

2024-05-03 00:27 UTC, rhuanpk commented on .gitignore
> +
linhas em branco desnecessárias
```suggestion
```

2024-05-03 00:27 UTC, rhuanpk commented on docker-compose.yaml
> +         MYSQL_PASSWORD: ${MYSQL_PASSWORD:-4DM1N@_2O2A}
já que esse valores serão os default e ficaram _hard coded_, talvez fique mais práticos valores simples
```suggestion
         MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
         MYSQL_DATABASE: ${MYSQL_DATABASE:-db}
         MYSQL_USER: ${MYSQL_USER:-admin}
         MYSQL_PASSWORD: ${MYSQL_PASSWORD:-admin}
```

2024-05-03 00:27 UTC, rhuanpk commented on docker-compose.yaml
> +         - "3306:3306"
a princípio, não acho que seja necessário expor a porta do container do banco... no lugar podemos usar as `networks`
```suggestion
```

2024-05-03 00:27 UTC, rhuanpk commented on docker-compose.yaml
> +         - ./mysql:/var/lib/mysql
da forma atual na verdade não estará utilizando o volume declarado lá em baixo, mas sim a pasta `mysql` no diretório corrente
```suggestion
         - mysql-data:/var/lib/mysql
```

2024-05-03 00:27 UTC, rhuanpk commented on docker-compose.yaml
> +         - "8080:8080"
como a API rodará? talvez não seja necessário expor a porta do container para fora, mas somente para localhost
```suggestion
         - 8080
```

2024-05-06 18:22 UTC, diogenesviana approved these changes

2024-05-06 19:07 UTC, brunocamposousa approved these changes

2024-05-06 19:30 UTC, rhuanpk requested changes
Ok, as últimas alterações parecem boas, porém, ficou faltando implementar o recurso de `networks` que mencionei [nessa revisão](https://github.com/diogenesviana/fiap-tech-2024/pull/1#discussion_r1588547865). Caso esse recurso não exista, não sei se será possível a comunicação do banco de dados com o backend.

2024-05-06 21:37 UTC, rhuanpk requested changes

2024-05-06 21:37 UTC, rhuanpk commented on docker-compose.yaml
> +   internal-network:
Só faltou mesmo especificar o driver de rede, de resto está top!
```suggestion
networks:
   internal-network:
      driver: bridge
```

2024-05-06 22:46 UTC, rhuanpk approved these changes
+1

2024-05-06 22:47 UTC, rhuanpk commented
Acredito que já pode ser mesclado.

2024-05-07 12:13 UTC, merged